// <auto-generated />
using System;
using CommonModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CommonModels.Migrations
{
    [DbContext(typeof(PokeAnalizeDbContext))]
    [Migration("20201015143955_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CommonModels.Battle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("EnemysFirstElection")
                        .HasColumnType("int");

                    b.Property<int?>("EnemysSecondElection")
                        .HasColumnType("int");

                    b.Property<int?>("EnemysThirdElection")
                        .HasColumnType("int");

                    b.Property<int>("MyFirstElection")
                        .HasColumnType("int");

                    b.Property<int>("MyPartyId")
                        .HasColumnType("int");

                    b.Property<int>("MySecondElection")
                        .HasColumnType("int");

                    b.Property<int>("MyThirdElection")
                        .HasColumnType("int");

                    b.Property<int?>("Ranking")
                        .HasColumnType("int");

                    b.Property<bool?>("Win")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("MyPartyId");

                    b.ToTable("Battles");
                });

            modelBuilder.Entity("CommonModels.Party", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Parties");
                });

            modelBuilder.Entity("CommonModels.Pokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte?>("Attack")
                        .HasColumnType("tinyint");

                    b.Property<int?>("BattleId")
                        .HasColumnType("int");

                    b.Property<byte?>("Defense")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("HP")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(6)")
                        .HasMaxLength(6);

                    b.Property<decimal>("No")
                        .HasColumnType("decimal(3,0)");

                    b.Property<int?>("PartyId")
                        .HasColumnType("int");

                    b.Property<byte?>("SpAtk")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("SpDef")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("Speed")
                        .HasColumnType("tinyint");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Type2")
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.HasIndex("BattleId");

                    b.HasIndex("PartyId");

                    b.ToTable("Pokemons");
                });

            modelBuilder.Entity("CommonModels.Battle", b =>
                {
                    b.HasOne("CommonModels.Party", "MyParty")
                        .WithMany()
                        .HasForeignKey("MyPartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommonModels.Pokemon", b =>
                {
                    b.HasOne("CommonModels.Battle", null)
                        .WithMany("Pokemons")
                        .HasForeignKey("BattleId");

                    b.HasOne("CommonModels.Party", null)
                        .WithMany("Pokemons")
                        .HasForeignKey("PartyId");
                });
#pragma warning restore 612, 618
        }
    }
}
